### ISSUE TITLE
"end of central directory record signature not found" during initialize-email-theme on v.10.0.0

### ISSUE THREAD

**Issue by ckbaker10** [keycloakify/keycloakify-starter#25]
Hello,

I've noticed that on yesterdays release the "initialize-email-theme" is broken with the error

```
Initialize with the base email theme from which version of Keycloak?
Error: end of central directory record signature not found
    at /opt/rundeck-gits/customizing-engel/node_modules/keycloakify/bin/430.index.js:734:14
    at /opt/rundeck-gits/customizing-engel/node_modules/keycloakify/bin/430.index.js:1178:5
    at /opt/rundeck-gits/customizing-engel/node_modules/keycloakify/bin/430.index.js:214:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
```

**Comment by garronej** [comment]
Hello @ckbaker10,  

Thank you for reporting, it has been fixed in the last release of Keycloakify
