### ISSUE TITLE
Error on account theme with multiple pages in local keycloak container

### ISSUE THREAD

**Issue by deincodeverbesserer93** [keycloakify/keycloakify-starter#35]
Hello @garronej ,
sorry that i have another error :). I want to test my keycloakify theme in my own local docker  keycloak engine. Not yours with **npx keycloakify start-keycloak**.

I have the following error, when i login to the "account-theme". The login works but the error occurs on the account

In the browser
<img width="1750" alt="Bildschirmfoto 2024-09-23 um 18 34 38" src="https://github.com/user-attachments/assets/e68eb62a-d332-4009-81a8-ada52a9f13b0">

In Keycloak console

```
backend-keycloak-1  | 2024-09-23 16:29:27,613 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.NoClassDefFoundError: org/keycloak/services/ForbiddenException
backend-keycloak-1  |   at org.keycloak.services.resources.account.AccountFormServiceFactory.create(AccountFormServiceFactory.java:47)
backend-keycloak-1  |   at org.keycloak.services.resources.account.AccountFormServiceFactory.create(AccountFormServiceFactory.java:21)
backend-keycloak-1  |   at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:195)
backend-keycloak-1  |   at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.getProvider(Unknown Source)
backend-keycloak-1  |   at org.keycloak.services.resources.account.AccountLoader.getAccountResourceProvider(AccountLoader.java:172)
backend-keycloak-1  |   at org.keycloak.services.resources.account.AccountLoader.getAccountService(AccountLoader.java:86)
backend-keycloak-1  |   at org.keycloak.services.resources.account.AccountLoader$quarkusrestinvoker$getAccountService_265aa1aaf86cc2a5ca4d1c819f2a826c7dc11dc0.invoke(Unknown Source)
backend-keycloak-1  |   at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
backend-keycloak-1  |   at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
backend-keycloak-1  |   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
backend-keycloak-1  |   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
backend-keycloak-1  |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
backend-keycloak-1  |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
backend-keycloak-1  |   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
backend-keycloak-1  |   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
backend-keycloak-1  |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend-keycloak-1  |   at java.base/java.lang.Thread.run(Thread.java:1583)
backend-keycloak-1  | Caused by: java.lang.ClassNotFoundException: org.keycloak.services.ForbiddenException
backend-keycloak-1  |   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
backend-keycloak-1  |   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
backend-keycloak-1  |   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
backend-keycloak-1  |   at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
backend-keycloak-1  |   at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
backend-keycloak-1  |   ... 17 more
backend-keycloak-1  | 

```

Thats my changes:
- run docker-compose.yml with keycloak 25.0.5
- npx keycloakify initialize-account-theme
- multiple
- npx keycloakify eject-page   
- account.ftl
- extend the switch case in KcPage.tsx and KcPageStory.tsx
- npm run build-keycloak-theme   
- select jar-file in my docker-compose.yml
- select login / account theme
- create new user
- login as new user in new realm
- above errors occurs

Have you any ideas?

**Comment by garronej** [comment]
Hello again @deincodeverbesserer93,

> Any new ideas?

Unfortunately, no :(

Since it works with the testing container and for everyone else, I assume there's something specific in your configuration that's triggering the bug.  
If you can reproduce the issue in the testing container, I'll be able to fix it. Otherwise, I'm not sure how to proceed.

By the way, the title of the issue seems unrelated to the description. You might want to update it for clarity.

**Comment by garronej** [comment]
Cool that you found the error!  
I don't understand though.  
The two dots look very sketch to me. Where did you get thoses?

**Comment by deincodeverbesserer93** [comment]
I think java has at the end has problems with the naming changes on underscore and a dot.
